### ISSUE TITLE
Thanks for making this data open

### ISSUE THREAD

**Issue by bw4sz** [nightonion/yosemite-tree-dataset#2]
Just read the paper. Thanks for your work. I am the developer of https://deepforest.readthedocs.io/ and the NeonTreeEvaluation dataset. Great to see it used. Couple questions.

1. How can I make the dataset better to help others find/use it?
2. Did you try using deepforest to count the trees in the blocks? Judging from the results, it looks like you did not. i'd be interested in understanding the performance difference. I get constantly asked for deepforest to be applied in lower resolution data.
3. How did you access google maps high resolution data? What is the process of getting those data? Costs?

All thoughts welcome. Thanks again.

**Comment by nightonion** [comment]
Hi Ben,

Thanks for the comments.

1. Please feel free to fork the dataset and modify it if you want. You are very welcome to try it.

2. We didn't try deepforest in this paper. But currently, several members in my lab are trying deepforest on tree detection projects. We will report the performance in our future works.

3. The high-resolution map is savable in the desktop version of Google Earth Pro. But actually, we used a software called Map Puzzle for bulky download. Initially, we downloaded the images at `zoom = 21` (about 17 pixels / meter). Then we stitched them into a whole big picture using PIL package in Python. Finally, we resized the big picture by 0.5X. 

Guang Chen

**Comment by bw4sz** [comment]
awesome. Always happy to help, make issues on our repos if you need anything.
